### ISSUE TITLE
Feature Request - Add flow attribute arrays to output

### ISSUE THREAD

**Issue by gideonshalev** [Viasat/network-stats#3]
Please add the following flow attribute arrays:
1) packet arrival timestamp (bigint, millisecond resolution)
2) packet size
3) packet direction (FL/RL)

Please also add a command-line flag to allow control of whether or not to add these arrays to the output (default = True).

**Comment by charles-laubach** [comment]
Implemented in commits:
6f77a4b12bda61eabfaa27b2f96159f301694d14
44d5373f6e372e585fd02a8ca0f585ce205a7cc8

Fully implemented and tested. Rather than a flag, as suggested, a new output was created for an 'extended csv'.
