### ISSUE TITLE
file_splitter.py should accept user-specified split duration parameter

### ISSUE THREAD

**Issue by dvrx** [Viasat/network-stats#5]
Currently file_splitter splits a network-stats capture file into 5-minute chunks.  The user should be able to specify an optional duration parameter, in case they want chunks of different lengths (in minutes).  I don't see a need to over-complicate this by allowing users to specify finer-grained chunk lengths (e.g., to the second).

**Comment by charles-laubach** [comment]
Enhancement implemented
